[package]
name = "rust_interop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.0", features = ["napi4", "tokio_rt"] }
napi-derive = "2.12.0"
libc = "0.2"
term_size = "0.3.2"

[build-dependencies]
napi-build = "2.0.1"
